apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: core
  annotations:
    cert-manager.io/issuer: letsencrypt
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,dateFull,content-type-full,content-MD5
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: {{ include "core.url" . }}
    nginx.ingress.kubernetes.io/enable-access-log: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/enable-error-log: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/use-regex: "true"

    # https://stackoverflow.com/a/73548785
    nginx.org/client-max-body-size: "0"
    nginx.org/proxy-connect-timeout: 3600s
    nginx.org/proxy-read-timeout: 3600s
    nginx.org/proxy-send-timeout: 3600s
spec:
  ingressClassName: public
  rules:
    - host: {{ .Values.global.domainName }}
      http:
        paths:
          - path: /server
            pathType: Prefix
            backend:
              service:
                name: core
                port:
                  number: {{ .Values.core.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: core
                port:
                  number: {{ .Values.core.port }}
          - path: /iam
            pathType: Prefix
            backend:
              service:
                name: iam
                port:
                  number: {{ .Values.iam.port }}
          - path: /cbir
            pathType: Prefix
            backend:
              service:
                name: cbir
                port:
                  number: {{ .Values.cbir.port }}
          - path: /sam
            pathType: Prefix
            backend:
              service:
                name: sam
                port:
                  number: {{ .Values.sam.port }}
          - path: /ims/formats
            pathType: Prefix
            backend:
              service:
                name: pims
                port:
                  number: {{ .Values.pims.port }}
          - path: /ims/image/upload
            pathType: Prefix
            backend:
              service:
                name: pims
                port:
                  number: {{ .Values.pims.port }}
          - path: /ims/import
            pathType: Prefix
            backend:
              service:
                name: pims
                port:
                  number: {{ .Values.pims.port }}
          - path: /ims/upload
            pathType: Prefix
            backend:
              service:
                name: pims
                port:
                  number: {{ .Values.pims.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-ui
                port:
                  number: {{ .Values.web_ui.port }}
  tls:
  - hosts:
    - {{ include "core.hostname" . }}
    secretName: ingress-tls
