apiVersion: v1
kind: Secret
metadata:
  name: core-secret
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "core-secret") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  ADMIN_PASSWORD: {{ get $secretData "ADMIN_PASSWORD" | default (randAlphaNum 64 | b64enc) | quote }}
  ADMIN_PRIVATE_KEY: {{ get $secretData "ADMIN_PRIVATE_KEY" | default (uuidv4 | b64enc) | quote }}
  ADMIN_PUBLIC_KEY: {{ get $secretData "ADMIN_PUBLIC_KEY" | default (uuidv4 | b64enc) | quote }}
  JWT_SECRET: {{ get $secretData "JWT_SECRET" | default (randAlphaNum 64 | b64enc) | quote }}
  SUPER_ADMIN_PRIVATE_KEY: {{ get $secretData "SUPER_ADMIN_PRIVATE_KEY" | default (uuidv4 | b64enc) | quote }}
  SUPER_ADMIN_PUBLIC_KEY: {{ get $secretData "SUPER_ADMIN_PUBLIC_KEY" | default (uuidv4 | b64enc) | quote }}
  IMAGE_SERVER_PRIVATE_KEY: {{ get $secretData "IMAGE_SERVER_PRIVATE_KEY" | default (uuidv4 | b64enc) | quote }}
  IMAGE_SERVER_PUBLIC_KEY: {{ get $secretData "IMAGE_SERVER_PUBLIC_KEY" | default (uuidv4 | b64enc) | quote }}
  SMTP_PASSWORD: {{ get $secretData "SMTP_PASSWORD" | default (randAlphaNum 64 | b64enc) | quote }}
  JAVAMELODY_PASS: {{ get $secretData "JAVAMELODY_PASS" | default (randAlphaNum 64 | b64enc) | quote }}
---
