apiVersion: v1
kind: ConfigMap
metadata:
  name: iam
data:
  KC_BOOTSTRAP_ADMIN_USERNAME: admin
  KC_PROXY_HEADERS: xforwarded
  KC_HTTP_RELATIVE_PATH: /iam
  KC_HTTP_ENABLED: "true"
  KC_HTTP_PORT: "{{ .Values.iam.port }}"
  KC_HOSTNAME_STRICT: "false"
  KC_HOSTNAME_STRICT_HTTPS: "false"
  KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
  KC_FEATURES: token-exchange
  KC_DB_USERNAME: iam
  KC_DB_URL_DATABASE: iam
  KC_DB_URL_HOST: postgres-iam.{{ .Release.Namespace }}.svc.cluster.local
  KC_DB_URL_PORT: "5432"
  KC_HOSTNAME: "{{ .Values.global.domainName }}"
  # KC_HOSTNAME_ADMIN: aaa_config.CYTOMINE_HOST
  # KC_ADMIN_EMAIL: cytomine@uliege.be
  # KC_SMTP_HOST: smtp.HOST
  # KC_SMTP_PORT: smtp.PORT
  # KC_SMTP_USER: smtp.USER
  # KC_SMTP_PASS: smtp.PASS
  # KC_SMTP_FROM: smtp.FROM

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: iam-client-config
data:
  config.json: |-
    {
      "clientId" : "core",
      "name" : "Cytomine Core",
      "description" : "This is the default client for cytomine.",
      "rootUrl" : "https://{{ .Values.global.domainName }}",
      "adminUrl" : "https://{{ .Values.global.domainName }}",
      "baseUrl" : "https://{{ .Values.global.domainName }}",
      "surrogateAuthRequired" : false,
      "enabled" : true,
      "alwaysDisplayInConsole" : false,
      "clientAuthenticatorType" : "client-secret",
      "defaultRoles" : [ "USER" ],
      "redirectUris" : [ "https://{{ .Values.global.domainName }}/*" ],
      "webOrigins" : [ "*" ],
      "notBefore" : 0,
      "bearerOnly" : false,
      "consentRequired" : false,
      "standardFlowEnabled" : true,
      "implicitFlowEnabled" : false,
      "directAccessGrantsEnabled" : true,
      "serviceAccountsEnabled" : false,
      "publicClient" : true,
      "frontchannelLogout" : true,
      "protocol" : "openid-connect",
      "attributes" : {
        "realm_client" : "false",
        "oidc.ciba.grant.enabled" : "false",
        "backchannel.logout.session.required" : "true",
        "login_theme" : "keycloak",
        "post.logout.redirect.uris" : "https://{{ .Values.global.domainName }}/*",
        "display.on.consent.screen" : "false",
        "oauth2.device.authorization.grant.enabled" : "false",
        "backchannel.logout.revoke.offline.tokens" : "false"
      },
      "authenticationFlowBindingOverrides" : { },
      "fullScopeAllowed" : true,
      "nodeReRegistrationTimeout" : -1,
      "defaultClientScopes" : [ "web-origins", "acr", "roles", "profile", "basic", "email" ],
      "optionalClientScopes" : [ "address", "phone", "offline_access", "microprofile-jwt" ]
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: iam-user-config
data:
  config.json: |-
    {
      "username": "admin",
      "enabled": true,
      "emailVerified": true,
      "email": "admin@cytomine.org",
      "firstName": "Admin",
      "lastName": "Admin"
    }
