server:
  tomcat:
    basedir: /tmp/appengine
  port: ${PORT:8080}
spring:
  servlet:
    multipart:
      max-file-size: 15GB
      max-request-size: 15GB
      location: /tmp/appengine/uploads
      enabled: false
  datasource:
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USERNAME}
  hibernate:
    ddl-auto: drop-create
    show-sql: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    generate-ddl: true
  liquibase:
    enabled: true
    change-log: classpath:master-changelog.yml
  security:
    basic:
      enabled: false
    ignored: ${API_PREFIX:/api/}\*\*
  management:
    security:
      enabled: false
  jackson:
    serialization:
      fail-on-empty-beans: false
storage:
  base-path: ${STORAGE_BASE_PATH:/data}
  impl: ${STORAGE_IMPL:filesystem} # possible values [filesystem]
  input:
    charset: UTF_8 # possible values [UTF_8,US_ASCII,ISO_8859_1,UTF_16LE,UTF_16BE,UTF_16] and UTF_8 is default
registry:
  url: ${REGISTRY_URL}
  user: ${REGISTRY_USER:}
  password: ${REGISTRY_PASSWORD:}
scheduler:
  impl: default # possible values [default]
  task-resources:
    cpus: 1
    ram: 4Gi
  helper-containers-resources:
    cpu: 1
    ram: 1Gi
  run:
    mode: ${SCHEDULER_RUN_MODE:local} # possible values [local,cluster]
    storage-base-path: ${RUN_STORAGE_BASE_PATH:/data} # directory in host
  datasets-path: ${REF_STORAGE_BASE_PATH:/data/datasets} # directory in host contains bigpicture datasets
  advertised-url: ${SCHEDULER_ADVERTISED_URL} # The URL of the app engine, to be requested from the running tasks
  registry-advertised-url: ${SCHEDULER_REGISTRY_ADVERTISED_URL}
  use-host-network: ${SCHEDULER_USE_HOST_NETWORK}
  tasks-namespace: ${SCHEDULER_TASKS_NAMESPACE}
logging:
  level:
    root: ERROR
    be.cytomine.appengine: INFO
app-engine:
  version: ce-0.0.0 # do not modify this, it will be replaced during build (ci)
  api_version: v1
  api_prefix: ${API_PREFIX:/api/}
