services:

  pims:
    image: cytomine/pims:dev-latest
    build:
      context: ./pims
      target: dev-server
    ports:
      - "${DEV_PIMS_PORT:-5000}:5000"
      - "${DEV_SSH_PIMS_PORT:-10024}:22"
    command: ["/bin/bash"]
    stdin_open: true
    tty: true
    volumes:
      - ./pims:/app
    environment:
      DEBUG: true
      WEB_CONCURRENCY: 1 # only one process in dev

  pims-cache:
    ports:
      - "${DEV_PORT_REDIS:-6379}:6379"
