services:

  sam:
    image: cytomine/sam:dev-latest
    build:
      context: ./sam
      target: dev-server
    ports:
      - "${DEV_SAM_PORT:-8000}:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    stdin_open: true
    tty: true
    volumes:
      - ./sam:/app
