apiVersion: v1
kind: ConfigMap
metadata:
  name: app-engine
data:
  DB_USERNAME: appengine
  DB_NAME: appengine
  DB_HOST: postgres-app-engine.{{ .Release.Namespace }}.svc.cluster.local
  DB_PORT: "5432"
  API_PREFIX: /app-engine/
  REGISTRY_URL: http://registry.container-registry.svc.cluster.local:5000
  SCHEDULER_ADVERTISED_URL: http://app-engine.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.app_engine.port }}
  SCHEDULER_REGISTRY_ADVERTISED_URL: localhost:32000
  SCHEDULER_USE_HOST_NETWORK: "false"
  SCHEDULER_RUN_MODE: "cluster"
  SCHEDULER_TASKS_NAMESPACE: {{ include "cytomine.appEngineTasksNamespace" . }}
