apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-engine
  namespace: {{ include "cytomine.appEngineTasksNamespace" . }}

---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: app-engine
  namespace: {{ include "cytomine.appEngineTasksNamespace" . }}
  annotations:
    kubernetes.io/service-account.name: app-engine

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-engine
  namespace: {{ .Release.Namespace }}
{{ if .Values.images.imagePullSecretsNames }}
imagePullSecrets:
{{- range .Values.images.imagePullSecretsNames }}
- name: {{ . }}
{{- end }}
{{ end }}

---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: app-engine
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: app-engine

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role # we need to restrict that by namespace (Role not ClusterRole)
metadata:
  name: pod-starter-for-{{ include "cytomine.appEngineTasksNamespace" . }}
  namespace: {{ include "cytomine.appEngineTasksNamespace" . }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["post","get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-starter-app-engine-{{ include "cytomine.appEngineTasksNamespace" . }}
  namespace: {{ include "cytomine.appEngineTasksNamespace" . }}
subjects:
- kind: ServiceAccount
  name: app-engine
  apiGroup: ""
  namespace: {{ include "cytomine.appEngineTasksNamespace" . }}
- kind: ServiceAccount
  name: app-engine
  apiGroup: ""
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: pod-starter-for-{{ include "cytomine.appEngineTasksNamespace" . }} # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: ""
