global:
  domainName: 'cytomine.local'

postgresql:
  storageClassName: 'local-path'
pims:
  imageStorage:
    storageClassName: 'local-path'
  tempImageStorage:
    storageClassName: 'local-path'
  datasetImportFolder: '/data/dataset'
mongodb:
  storageClassName: 'local-path'
app_engine:
  tasks_namespace: cytomine-local-tasks

ingress:
  className: nginx
