name: Docker push PR

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      REGISTRY_USERNAME:
        required: true
      REGISTRY_TOKEN:
        required: true
jobs:
  build-push:
    runs-on: self-hosted

    strategy:
      fail-fast: true
      matrix:
        image:
          - name: app-engine
            context: '.'
            dockerfile_location: app-engine
          - name: cbir
          - name: core
          - name: iam
          # - name: mongo
          - name: nginx
          - name: pims
            context: '.'
            dockerfile_location: pims
          - name: postgis
          - name: sam
          - name: web-ui
          - name: python-client
            context: clients/python

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.1
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Cytomine registry
        uses: docker/login-action@v3
        if: github.ref_name != 'main'
        with:
          registry: registry.cytomine.org
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        if: github.ref_name == 'main'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.image.context || matrix.image.name }}
          file: ./${{ matrix.image.dockerfile_location || matrix.image.context || matrix.image.name }}/Dockerfile
          push: true
          tags: ${{ (github.ref_name != 'main' && 'registry.cytomine.org/') || '' }}cytomine/${{ matrix.image.name }}:${{ github.ref_name == 'main' && 'latest' || github.sha }}
          allow: network.host
          network: host
