name: IMS

on:
  workflow_call:

permissions:
  contents: read

jobs:
  lint:
    runs-on: self-hosted

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
          version: ${{ vars.UV_VERSION }}

      - name: Lint
        run: uv --directory ./pims run ruff check

  tests:
    runs-on: self-hosted

    steps:
      - name: Set up the repository
        uses: actions/checkout@v6.0.1

      - name: Install system dependencies
        run: |
          sudo apt-get -y update && \
          sudo apt-get -y install --no-install-recommends --no-install-suggests \
            libopenslide-dev \
            libopenjp2-7-dev \
            libvips42 \
            libpng-dev

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
          version: ${{ vars.UV_VERSION }}

      - name: Run tests
        run: uv --directory ./pims run pytest tests
        env:
          CONFIG_FILE: ./tests/pims-config.env
